### PR TITLE
Migrate to PropTypes from React.PropTypes

### PR DESCRIPTION
**Pull request by justinchen**
React 16 moved PropTypes to a standalone library.  This commit adds the package and changes calls to `React.PropTypes` to `PropTypes`.

### CODE REVIEW

**Comment by freeranger** [comment]
Thanks @justinchen - Have you tested that the demo site still works, or does that need a PR also?
https://github.com/freeranger/react-bootstrap-tabs-demo

**Comment by justinchen** [comment]
@freeranger I just confirmed the demo works once you add the `prop-types` package.

**Comment by freeranger** [comment]
Thanks @justinchen.
I just tried to npm install locally so I can test out the change and I am getting:
`ReferenceError: Unknown plugin "'transform-es2015-modules-umd'" specified in "base" at 0, attempted to resolve relative to "src"
`
I don't know if this is related to your change or something in babel - I will have to investigate further.
What version of babel did  you end up with when you did npm install?

**Comment by justinchen** [comment]
@freeranger It grabbed 6.26.0 for me.

**Comment by freeranger** [comment]
@justinchen ok thanks.  I was using an unfamiliar machine - I will try again at the weekend from my regular dev box..

**Comment by freeranger** [comment]
Thanks @justinchen - all merged in now.

**Comment by justinchen** [comment]
@freeranger great, thanks!

**Pull request merged**
